version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    environment:
      - PYTHONUNBUFFERED=1

  bot:
    build: ./bot
    volumes:
      - ./bot:/app
      - ./reports:/app/reports
    depends_on:
      - api